### ISSUE TITLE
Memory issue on ESP8266

### ISSUE THREAD

**Issue by mrave** [chrisb2/micropython-fingerprint#1]
Trying to import PyFingerprint returns: 
```
>>> import os                                                                                                                                         
>>> from pyfingerprint import PyFingerprint                                                                                                           
Traceback (most recent call last):                                                                                                                    
  File "<stdin>", line 1, in <module>                                                                                                                 
MemoryError: memory a                                                                                                                                 
>>> 
```

My board is:
esptool.py v3.0
```
Serial port COM3
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: ec:fa:bc:2e:c3:3d
Uploading stub...
Running stub...
Stub running...
Manufacturer: 68
Device: 4016
Detected flash size: 4MB
```

Any idea?

**Comment by chrisb2** [comment]
That will be because this module is to big to fit into ram, you will need to build micropython, see https://github.com/micropython/micropython/tree/master/ports/esp8266 having first put this module in the modules directory. 

Chris

**Comment by chrisb2** [comment]
The other alternative is to use mpy_cross to compile this module to byte code, you should find instructions for this on the web.

Chris

**Comment by mrave** [comment]
Thanks I have actually built the firmware and added it as a frozen module - thanks!
I still wasn't able to reach the sensor, as it used the serial, and interfere with REPL. I tried WebREPL and to detach it (uos.dupterm(uart, 1)) but handshake is still frozen... any idea how to debug it?

**Comment by chrisb2** [comment]
Sounds like you are doing the right thing based on https://forum.micropython.org/viewtopic.php?f=16&t=7322&p=47346&hilit=uart+detach#p41667, but I do not know how to debug this. I suggest you ask about this on the forum.

Chris

**Comment by chrisb2** [comment]
Closing for now, please re-open if you need further help.
