### ISSUE TITLE
Fingers do not match...

### ISSUE THREAD

**Issue by stanisljevic** [chrisb2/micropython-fingerprint#2]
Hi Chris, 
I have some strange problem, seems that whenever i try to enroll the finger i get error that fingers do not match.
I use example from Bastian from file example_enroll.py as you suggest with no luck.
All test of sensor are passing and I use R503 sensor on ESP32.
Also if I skip condition `compareCharacteristics` then enrollment succeeds and when i try to search he found the template but i get error on downloading characteristics `downloadCharacteristics(FINGERPRINT_CHARBUFFER1)`.
Do you have any idea what can be wrong, thanks in advance?

**Comment by chrisb2** [comment]
I think I recall having a similar issue. This is my function to record a finger print which works for me. `self.__sensor` is an instance of _PyFingerprint_ class as per example code.
```
    def recordFingerPrint(self):
        """Take finger print and store."""
        self.__takePrint(0x01)

        # Checks if finger is already enrolled
        result = self.__sensor.searchTemplate()
        positionNumber = result[0]
        if (positionNumber >= 0):
            raise Exception('Finger already stored at #%d' % positionNumber)

        print('Remove finger...')
        time.sleep(1)

        self.__takePrint(0x02)

        # Compares the charbuffers
        if (self.__sensor.compareCharacteristics() == 0):
            raise Exception('Fingers do not match!')

        # Creates a template and store template
        self.__sensor.createTemplate()
        positionNumber = self.__sensor.storeTemplate()
        print('Recorded and stored at #%d' % positionNumber)

    def __takePrint(self, charbuffer):
        print('Place finger on sensor...')
        while (not self.__sensor.readImage()):
            pass

        # Convert read image to characteristics and store it in charbuffer
        self.__sensor.convertImage(charbuffer)
        self.__sensor.createTemplate()
```

Chris

**Comment by stanisljevic** [comment]
Thanks Chris,
i use simalar method and i managed at last to make it work, but I'm calling createTemplate() method after calling readImage twice and then compareCharacteristics() and now it works, it's strange.
